### ISSUE TITLE
Error when adding a text from a collection that is more than 3 levels deep

### ISSUE THREAD

**Issue by sonofmun** [Formulae-Litterae-Chartae/formulae-capitains-nemo#432]
```
2020-09-16 13:07:48,072 ERROR: Exception on /add_text/urn:cts:formulae:marmoutier_manceau/urn:cts:formulae:mondsee.rath0067.lat001/1 [GET] [in /home/ubuntu/env/lib/python3.7/site-packages/flask/app.py:1786]
Traceback (most recent call last):
  File "/home/ubuntu/env/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/env/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/env/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/env/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/ubuntu/env/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/env/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/env/lib/python3.7/site-packages/flask_nemo/__init__.py", line 783, in route
    return self.route(getattr(instance, name), **kwargs)
  File "/home/ubuntu/env/lib/python3.7/site-packages/flask_nemo/__init__.py", line 854, in route
    new_kwargs = fn(**kwargs)
  File "/home/ubuntu/formulae-capitains-nemo/formulae/nemo.py", line 882, in r_add_text_corpus
    initial.update({'prev_texts': objectIds, 'prev_reffs': reffs})
AttributeError: 'Response' object has no attribute 'update'
```

**Comment by sonofmun** [comment]
Fixed with #440
